jdbcSettings:
  url: "jdbc:mysql://mysql.cc.puv.fi:3306/e1800950_northwind"
  username: "e1800950"
  password: "QdUD4yYxCwcj"
  driverClassName: "com.mysql.jdbc.Driver"

packageName: "fi.vamk.e1800950.northwind"